# from .polynomialsUtils import *

# One = 1
# Two = 2
# Three = 3
# Four = 4
# Five = 5
# Six = 6
# Seven = 7
# Eight = 8
# Nine = 9
# Ten = 10
# Eleven = 11
# Twelve = 12
# Thirteen = 13
# Fourteen = 14
# Fifteen = 15
# Sixteen = 16
# Seventeen = 17
# Eighteen = 18
# Nineteen = 19
# Twenty = 20

# class QuestionManager:
#     def __init__(self, variation):
#         self.variation = variation
#         self.initialize_attributes()

#     def initialize_attributes(self):
#         if self.variation == 1:
#             self.polynomial = gen_polynomial()
#             problem = '1. When ' + self.polynomial + ' is divided by ' + self.divisor = ' the remainder is 26, find k.'

            
#         elif self.variation == 2:
#             problem2 = 'If ' + divisor + ' is a factor of ' + polynomial + 'then ,find k.'
#             self.attribute1 = 'Special Value'
#             self.attribute2 = 20
#         elif self.variation == 3:
#             problem3 = 'The number of shirts sold by the shopkeeper is given by the expression ' + factor1 +' . The price per shirt is given by the expression ' +factor2 + \
#                 ' . Find the total amount of revenue earned by the shopkeeper by selling the shirts.'
#             self.attribute1 = 'Custom Value'
#             self.attribute2 = 30
#         elif self.variation == 4:
#             problem4 = 'The number of tablets sold by a shop can be modeled by the expression ' + exp1 + ' and price per tablet is modeled by an expression ' + exp2 + ', where t is the number of months in a year. If we use self model, what is the total amount of revenue generated by the shop at the end of the year?'
#             self.attribute1 = 'Special Value'
#             self.attribute2 = 20
#         elif self.variation == 5:
#             problem5 = 'At the ruins of Caesarea, archeologists discovered a huge hydraulic concrete block with a volume of ' + volume + ' cubic meters. \
#                 The block’s dimensions are ' + height + ' meters high, ' + length + ' meters long, and ' + width + ' meters wide. What is the height of the block?'
#             self.attribute1 = 'Custom Value'
#             self.attribute2 = 30
#         elif self.variation == 6:
#             self.attribute1 = 'Special Value'
#             self.attribute2 = 20
#         elif self.variation == 7:
#             self.attribute1 = 'Custom Value'
#             self.attribute2 = 30
#         elif self.variation == 8:
#             self.attribute1 = 'Special Value'
#             self.attribute2 = 20
#         elif self.variation == 9:
#             self.attribute1 = 'Custom Value'
#             self.attribute2 = 30
#         elif self.variation == 1:
#             self.attribute1 = 'Custom Value'
#             self.attribute2 = 30
#         else:
#             raise ValueError(f"Unknown mode: {self.mode}")

#     def __repr__(self):
#         return f"ConditionalClass(mode={self.mode}, attribute1={self.attribute1}, attribute2={self.attribute2})"



# problem6 = 'Find 𝑎 and 𝑏 if the polynomial ' + polynomial + ' is divisible by ' + divisor + '.'
# problem7 = 'Find 𝑎 and 𝑏 if the polynomial ' + polynomial + ' gives a remainder of ' + rem1 + ' and ' + rem2 + 'when divided by '+ div1+ + ' and ' + div2 + ' respectively.'
# problem8 = 'An online music store sells about ' + eq1yInt + ' songs each day when it charges ' + eq2yInt + ' dollars per song. \
#     For each ' +eq2slope+ ' dollars increase in price, about ' + eq1slope + ' fewer songs per day are sold. \
#         Determine the price per song that will make (i.) zero revenue and (ii) maximum revenue, then give (iii) maximum revenue.'
# problem9 = 'A box with no top is to be formed by taking a rectangular piece of metal ' + length + ' by ' + width + ' cm and cutting a square of the same size out of each corner and folding up the sides. \
#     If the area of the base of the box is to be ' + area + ' square cm, (i) what should the length of the sides of the squares be and (ii) the dimension of the base?'
# problem10 = 'Suppose you throw a ball on an upward direction with an initial speed of ' + initialSpeed + ' m/s, that is ' +initialHeight + ' meters from the ground.\
#       If the acceleration of gravity is ' + gravity + 'meter per second squared, then (i) how long will it take to reach the ground, \
#         (ii) how long will it take to reach the maximum height, (iii) how long will it take to reach a height of ' + height + ' meters, and (iv) what is the maximum height?'

# # Define the questions
# # question1 = {'problem1': problem1}
# # question2 = {'problem2': problem2}
# # question3 = {'problem3': problem3}
# # question4 = {'problem4': problem4}
# # question5 = {'problem5': problem5}
# question6 = {'problem6': problem6}
# question7 = {'problem7': problem7}
# question8 = {'problem8': problem8}
# question9 = {'problem9': problem9}
# question10 = {'problem10': problem10}

# # Assign questions 1 to 10 to the easy list
# easy = [
#     question1,
#     question2,
#     question3,
#     question4,
#     question5,
# ]

# # Assign questions 6 to 10 to the hard list
# hard = [
#     question6,
#     question7,
#     question8,
#     question9,
#     question10
# ]
