

'1.When 𝑥^3+𝑘𝑥^2−4𝑥+2 + is divided by 𝑥 + 2  the remainder is 26, find k.'
'2.When 〖2𝑥〗^3−3𝑥^2+𝑘𝑥−1   is divided by 𝑥 −1  the remainder is 2, find k.'
'If  𝑥 −4 is a factor of  𝑥^4−𝑥^3−𝑘𝑥^2−11𝑥−4 ,find k.'
'Find 𝑎 and 𝑏 if the polynomial 𝑥^5−𝑎𝑥^2+𝑏  is divisible by 𝑥^2  −4 .'
'5. The number of shirts sold by the shopkeeper is given by the expression  3𝑥−5 . The price per shirt is given by the expression 2𝑥+1. Find the total amount of revenue earned by the shopkeeper by selling the shirts.'
'6. The number of tablets sold by a shop can be modeled by the expression 𝑁(𝑡)=7𝑡+25  and price per tablet is modeled by an expression 𝑃(𝑡)=3𝑡^2+3𝑡+36  , where t is the number of months in a year. If we use this model, what is the total amount of revenue generated by the shop at the end of the year?'
'''7. An online music store sells about 4000 songs each day when it charges $1 per song. For each $0.05 increase in price, about 80 fewer songs per day are sold. Determine the price per song that will make…
zero revenue
maximum revenue
'''
'8. A box with no top is to be formed by taking a rectangular piece of metal 20 by 24 cm and cutting a square of the same size out of each corner and folding up the sides. If the area of the base is to be 252 cm2, what should the length of the sides of the squares be?'
'9. At the ruins of Caesarea, archeologists discovered a huge hydraulic concrete block with a volume of 945 cubic meters. The block’s dimensions are x meters high, 12x-15 meters long, and 12x-21 meters wide. What is the height of the block?'
'''
10. Suppose you throw a ball on an upward direction with an initial speed of 10m/s from the ground. If the acceleration of gravity is -10m/𝑠^2,
 how long will it take to reach the ground? 
what is the maximum height? 
how long will it take to reach the maximum height? 
(Hint: Use the equation  ℎ(𝑥)=1/2 𝑔𝑡^2+𝑣_0 𝑡+ℎ_0   where 𝑔: is the acceleration of gravity, 𝑡 is the time, and 𝑣_0  𝑎𝑛𝑑  ℎ_0  are the initial velocity and height respectively.)

'''
